##------------------------------------------------------------------------------
## Two functions to create a special object that stores an 
## invertible matrix and caches its inverse
##------------------------------------------------------------------------------
## Example of usage
##------------------------------------------------------------------------------
## 1) generate an invertible square matrix
## 2) pass invertible square matrix to makeCacheMatrix
## 3) pass special "vector" object generated by makeCacheMatrix to cacheSolve 
##    which checks to see if the inverse matrix has already been calculated and 
##    if so, returns the inverse matrix from cache, and if not computes the 
##    inverse matrix else or return the inverse matrix from cache
##
##    mtrx <- matrix(rnorm(9),3,3)
##    imtrx <- makeCacheMatrix(mtrx)
##    cacheSolve(imtrx)
##------------------------------------------------------------------------------


## Create a special "vector" containing functions to:
## 1.    set the value of the matrix
## 2.    get the value of the matrix
## 3.    set the value of the inverse matrix in the cache
## 4.    get the value of the inverse matrix from the cache

makeCacheMatrix <- function(x = matrix()) {
    i <- NULL
    set <- function(y) {
        x <<- y
        i <<- NULL
    }
    get <- function() x
    setinverse <- function(solve) i <<- solve
    getinverse <- function() i
    list(set = set, get = get,
        setinverse = setinverse,
        getinverse = getinverse)
}


## Compute or retrieve from cache, the inverse of the matrix passed to makeCacheMatrix()

cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    i <- x$getinverse()
    if(!is.null(i)) {
        message("getting cached data")
        return(i)
    }
    data <- x$get()
    i <- solve(data, ...)
    x$setinverse(i)
    i
}

